### ISSUE TITLE
Console me

### ISSUE THREAD

**Issue by appt2** [CaiMuCheng/NodeJava#2]
Can you add a text editor where we type javascript code and see the result in a text view?

**Comment by CaiMuCheng** [comment]
No plan

**Comment by appt2** [comment]
I downloaded and installed the sample program and when I ran it, it didn't show anything, well it should work, let's understand it and find out if it really works or not.

**Comment by CaiMuCheng** [comment]
Please see your logcat

**Comment by appt2** [comment]
Great, just please write the main activity in Java so that I can participate, because I don't know anything about the project, when you add a console mode, I will start my participation with you.

**Comment by CaiMuCheng** [comment]
Now, I implemented JS call Java (really like rhino)

**Comment by appt2** [comment]
> Now, I implemented JS call Java (really like rhino)

I have not worked with the rhino library, but I know JavaScript, Java and C++
